name = "NumericalAnalysis"
uuid = "0d97b697-bd25-42f5-83fa-54c1184dd8d3"
authors = ["小雨 <xiaoyu@xiaoxiaoyu.me>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
